### ISSUE TITLE
주제선정

### ISSUE THREAD

**Issue by wjs4199** [Yejin-Yeon/2020OSS_team#2]
저희 주제 뭘로할까요?

**Comment by wjs4199** [comment]
주제 생각해놓으신거 있으신가요??ㅎㅎ 저는 책? 생각했었어요!

**Comment by Yejin-Yeon** [comment]
오오 약간 책 제목, 책의 종류, 가격, 작가 요런느낌으로요?

**Comment by wjs4199** [comment]
네네!! 책 제목, 장르, 가격, 별점, 페이지수 ....ㅎㅎ 등등으로요! 그러면 검색기능할때도 별점이나 페이지수로 함수를 만들 수 있을 것 같아서요!ㅎㅎ

**Comment by wjs4199** [comment]
근데 다른 것도 좋아요 ㅎㅎ 학우님 하고싶으신거 없으세요??

**Comment by Yejin-Yeon** [comment]
와 좋은것같아요! 저는 음료수 생각했었는데 책 한번 만들어보고싶네용ㅎㅎㅎ

**Comment by Yejin-Yeon** [comment]
책 만들어요 우리~!! ㅎㅎㅎ

**Comment by wjs4199** [comment]
허헛 ㅎㅎㅎ...그러면 책으로,..... 격한반응감사합니당...ㅋㅋㅋㅋㅋㅎㅎ

**Comment by wjs4199** [comment]
주제 닫을까요 그럼?ㅎㅎ

**Comment by Yejin-Yeon** [comment]
ㅋㅋㅋㅋㅋㅋㅋ 넹넹 그럼 역할 분담을 해볼까요?

**Comment by wjs4199** [comment]
넵 ㅎㅎ
