### ISSUE TITLE
역할분담&설계

### ISSUE THREAD

**Issue by Yejin-Yeon** [Yejin-Yeon/2020OSS_team#3]
역할분담 해보아요~!

**Comment by wjs4199** [comment]
저희가 함수를 10개만들어야하는데, CRUD랑 save, load, selectDataNo, search함수들 이렇게 해서 10개 채울수 있을 것 같아요!

**Comment by wjs4199** [comment]
혹시 read함수 만드실때 한개만 읽는 함수, list로 출력하는 함수 이렇게 2개로 만드셨나요??

**Comment by Yejin-Yeon** [comment]
그럼 5개씩 맡아볼까요?? CRUD 묶고 save, load묶는 것도 좋은 것 같아요!

**Comment by Yejin-Yeon** [comment]
네! list만들어서 그 안에서 read호출하게 했습니다!

**Comment by wjs4199** [comment]
근데 저희 헤더파일이랑 c파일 메인함수랑 구별해야하는 걸까요...?

**Comment by Yejin-Yeon** [comment]
음 우선은 함수만 정하면 될 것 같아요! 아 물론 구조체도용!

**Comment by Yejin-Yeon** [comment]
만약 자유라면 헤더를 만드는 것도 좋을것같아요~!

**Comment by wjs4199** [comment]
그러면 crud/save,load,검색 이렇게 나눌까요?

**Comment by wjs4199** [comment]
crud하는 사람이  main과 구조체를 만들어도 좋을 것 같아요!

**Comment by Yejin-Yeon** [comment]
그리고 메뉴 선택하는 함수도 필요한 것 같아요!

**Comment by Yejin-Yeon** [comment]
그럼 제가 CRUD하겠습니당!

**Comment by wjs4199** [comment]
그러면 1. selectMenu (메뉴판 보여주기)
2. create
3. read (한줄, 리스트)
4. update
5. delete

6. save
7. load
8. selectDataNo(원하는 번호입력)
9. searchName(이름 검색함수)
10. 추가적인 검색기능.

10. 별점 검색함수
11. 가격 검색함수

**Comment by wjs4199** [comment]
이런식으로 나누면 될까요??

**Comment by Yejin-Yeon** [comment]
네네! 그럼 5번까지 제가하고 list함수도 구현하는 방향으로 할게요!

**Comment by wjs4199** [comment]
네네! 그럼 제가 뒤에 맡아서 하겠습니다!! ㅎㅎ

**Comment by Yejin-Yeon** [comment]
아유 좋아요! 파이팅!

**Comment by wjs4199** [comment]
파이팅!
