### ISSUE TITLE
함수 구현 및 테스트하기

### ISSUE THREAD

**Issue by Yejin-Yeon** [Yejin-Yeon/2020OSS_team#5]
함수들을 구현해 보아요!!

**Comment by Yejin-Yeon** [comment]
.gitignore파일 만들었습니다! 모든 object파일들과 실행파일로 만들 book을 git에서 관리하지 않도록 추가하였습니당~!

**Comment by Yejin-Yeon** [comment]
헤더파일 Book.h만들었습니다! 그리고 Book 구조체 구현해놓았습니당:)

**Comment by wjs4199** [comment]
저도 manager.h와 manager.c 파일 만들고 saveData 함수 구현해놓았습니당!

**Comment by wjs4199** [comment]
manager.h 와 manager. c에 이외의 맡은 함수들(search 함수, load함수) 만들었고, 임시적인 main.c도 만들어놓았습니당!

**Comment by Yejin-Yeon** [comment]
네 확인했습니다 감사합니다!!

**Comment by Yejin-Yeon** [comment]
main.c 수정하고, book.h 완성했습니다!

**Comment by Yejin-Yeon** [comment]
book.c 구현하였고, Makefile만들어서 실행해 본 후, main.c오류 수정했습니다!!

**Comment by wjs4199** [comment]
main의 검색기능 조금 수정하고, readbook함수 조금 고쳤습니다!!ㅎㅎ

**Comment by Yejin-Yeon** [comment]
book.c 메뉴부분이랑 main.c 조금 수정했습니다!!:)

**Comment by wjs4199** [comment]
검색함수 주석처리했습니당!

**Comment by Yejin-Yeon** [comment]
Wiki 업데이트 했습니다~!!!

**Comment by Yejin-Yeon** [comment]
main.c book.c에 searching부분 주석처리하여 추가하였습니다!

**Comment by Yejin-Yeon** [comment]
main.c book.c searching 다시 추가하였습니다~!

**Comment by Yejin-Yeon** [comment]
main.c book.c book.h 정보 추가했습니당~!

**Comment by wjs4199** [comment]
main.c수정했습니다!

**Comment by wjs4199** [comment]
manager,c 에서 필요없는함수 부분 삭제 했습니다!

**Comment by Yejin-Yeon** [comment]
book.c에서 불필요한 부분 삭제했습니다~!

**Comment by Yejin-Yeon** [comment]
main.c menu1 추가했습니다~!

**Comment by wjs4199** [comment]
search 함수 2개 추가했습니다!

**Comment by Yejin-Yeon** [comment]
원격저장소를 https://github.com/wjs4199/2020OSS_teams.git 로 옮겼습니다!
